name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Run once to install dependencies
    #    apt-get update
    #    apt-get install -y cmake g++ libgtest-dev
    
    - name: Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j
    
    - name: Run test
      run: |
        ./build/unittest/E2ETest